"""add google auth and meet link fields

Revision ID: fc4c2442870e
Revises: 7a3679d41851
Create Date: 2026-04-14 22:27:50.721138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc4c2442870e'
down_revision: Union[str, None] = '7a3679d41851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('google_meet_url', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('meet_event_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_refresh_token', sa.Text(), nullable=True))
    # SQLite does not support ALTER COLUMN to change nullability;
    # password_hash is already nullable at the SQLite level for new inserts.
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_column('users', 'google_refresh_token')
    op.drop_column('users', 'google_id')
    op.drop_column('groups', 'meet_event_id')
    op.drop_column('groups', 'google_meet_url')
    # ### end Alembic commands ###
